# Generated by Django 4.1.7 on 2023-03-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_salary_currency_alter_joblisting_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='job_place',
            new_name='job_location',
        ),
    ]
